### ISSUE TITLE
Request to add pixhawk 2.4.8 in nuttx 

### ISSUE THREAD

**Issue by amitmanish** [PX4/NuttX#92]
I wanted to add pixhawk v2 to nuttx config for application development. Did a lot of effort following nuttx port guide but got error during make menuconfig . It would have been really appreciable if pixhawk could be added to nuttx.

**Comment by dagar** [comment]
@amitmanish this isn't immediately possible because the PX4 build is tightly integrated with NuttX. There's a NuttX defconfig for the pixhawk (https://github.com/PX4/Firmware/blob/master/platforms/nuttx/nuttx-configs/px4fmu-v2/nsh/defconfig), however nearly all of the board init lives on the PX4 side (https://github.com/PX4/Firmware/tree/master/src/drivers/boards/px4fmu-v2). 

If you want plain NuttX on a pixhawk the easiest thing to do is build PX4, but disable all the modules here. https://github.com/PX4/Firmware/blob/master/cmake/configs/nuttx_px4fmu-v2_default.cmake
